version: "1"
services:
  - type: web
    name: mrhouseklg-bot
    env: python
    region: oregon
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python bot.py"
    envVars:
      - key: PYTHON_VERSION
        value: "3.12.7"